<!-- #include file="../inc/top.asp" -->
<link rel="stylesheet" type="text/css" href="../inc/css/sub.css">

<div id="middle_sub">
	<!-- #include file="../inc/sub_visual.asp" -->
	
	<div class="navi_wrap">
		<div class="width_wrap">
			<span class="home">H</span><span class="block1">제품소개</span><span class="block2">Pipe</span>
		</div>
	</div>

	<div class="width_wrap">
		<!-- #include file="../inc/left.asp" -->
		<div id="contant">
			<h3 class="title">Pipe</h3>

			<!-- #include file="page2_tap.asp" -->
			
			<!-- #include file="page2_navi.asp" -->

			<h6 class="msg underline">스테인레스 강관 구조율표(STS 304기준)</h6>
			
			<div class="table_wrap" style="clear:both;">
				<STYLE type="text/css">
				
				.table_wrap table td{
					padding:10px 1px 10px 1px;
				}
				
				</STYLE>
				<TABLE cellspacing="0" cellpadding="0">
					<TR>
					  <th style="width:120px;" colspan="3">외 경</th>
					  <th colspan="20">두 께</th>
					</TR>
					<TR>
					  <th >1mm</th>
					  <th>A</th>
					  <th>inch</th>
					  <td>0.8</td>
					  <td>1.0</td>
					  <td>1.2</td>
					  <td>1.5</td>
					  <td>2.0</td>
					  <td>2.5</td>
					  <td>2.8</td>
					  <td>3.0</td>
					  <td>3.5</td>
					  <td>4.0</td>
					  <td>4.5</td>
					  <td>5.0</td>
					  <td>5.5</td>
					  <td>6.0</td>
					  <td>6.5</td>
					  <td>7.0</td>
					  <td>8.0</td>
					  <td>9.0</td>
					  <td>10</td>
					  <td>12</td>
					</TR>
					<TR>
					  <th>12.7</th>
					  <th>6A</th>
					  <th>1/2</th>
					  <td>2.00</td>
					  <td>1.95</td>
					  <td>1.90</td>
					  <td>1.90</td>
					  <td>1.90</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>13.8</th>
					  <th>8A</th>
					  <th>1/4</th>
					  <td>1.80</td>
					  <td>1.75</td>
					  <td>1.70</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>15.8</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>1.75</td>
					  <td>1.70</td>
					  <td>1.65</td>
					  <td>1.55</td>
					  <td>1.50</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>17.3</th>
					  <th>10A</th>
					  <th>3/8</th>
					  <td>1.70</td>
					  <td>1.60</td>
					  <td>1.50</td>
					  <td>1.45</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.50</td>
					  <td>1.50</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>19.1</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>1.65</td>
					  <td>1.50</td>
					  <td>1.45</td>
					  <td>1.40</td>
					  <td>1.30</td>
					  <td>1.30</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>21.7</th>
					  <th>15A</th>
					  <th>1/2</th>
					  <td>1.65</td>
					  <td>1.50</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.20</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>1.25</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>25.4</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>1.65</td>
					  <td>1.50</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.20</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>1.25</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>27.2</th>
					  <th>20A</th>
					  <th>3/4</th>
					  <td>1.65</td>
					  <td>1.50</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.20</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>1.25</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>31.8</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.40</td>
					  <td>1.35</td>
					  <td>1.20</td>
					  <td>1.15</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>34.0</th>
					  <th>25A</th>
					  <th>1</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>38.1</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>42.7</th>
					  <th>32A</th>
					  <th>1*1/4</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>48.6</th>
					  <th>40A</th>
					  <th>1*1/2</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>50.8</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>60.5</th>
					  <th>50A</th>
					  <th>2</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>63.5</th>
					  <th>&nbsp;</th>
					  <th>&nbsp;</th>
					  <td>&nbsp;</TD>
					  <td>1.45</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>76.3</th>
					  <th>65A</th>
					  <th>2*1/2</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.10</td>
					  <td>1.10</td>
					  <td>1.10</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>89.1</th>
					  <th>80A</th>
					  <th>3</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>101.6</th>
					  <th>90A</th>
					  <th>3*1/2</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>114.3</th>
					  <th>100A</th>
					  <th>4</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>139.8</th>
					  <th>125A</th>
					  <th>5</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>165.2</th>
					  <th>150A</th>
					  <th>6</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.15</td>
					  <td>1.12</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.07</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>216.3</th>
					  <th>200A</th>
					  <th>8</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.30</td>
					  <td>1.20</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.12</td>
					  <td>1.12</td>
					  <td>1.12</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>267.4</th>
					  <th>250A</th>
					  <th>10</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.30</td>
					  <td>1.20</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.12</td>
					  <td>1.12</td>
					  <td>1.12</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>318.5</th>
					  <th>300A</th>
					  <th>12</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.30</td>
					  <td>1.20</td>
					  <td>1.10</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.05</td>
					  <td>1.12</td>
					  <td>1.12</td>
					  <td>1.12</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>355.6</th>
					  <th>350A</th>
					  <th>14</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.43</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>406.4</th>
					  <th>400A</th>
					  <th>16</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.10</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.15</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.43</td>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					</TR>
					<TR>
					  <th>457.2</th>
					  <th>450A</th>
					  <th>18</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.26</td>
					  <td>1.26</td>
					  <td>1.26</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>&nbsp;</TD>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.70</td>
					</TR>
					<TR>
					  <th>508.0</th>
					  <th>500A</th>
					  <th>20</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.26</td>
					  <td>1.26</td>
					  <td>1.26</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>1.43</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.70</td>
					</TR>
					<TR>
					  <th>558.8</th>
					  <th>550A</th>
					  <th>22</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.20</td>
					  <td>1.26</td>
					  <td>1.26</td>
					  <td>1.26</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>1.43</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.70</td>
					</TR>
					<TR>
					  <th>609.6</th>
					  <th>600A</th>
					  <th>24</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>1.43</td>
					  <td>1.52</td>
					  <td>1.52</td>
					  <td>1.65</td>
					  <td>1.65</td>
					  <td>1.75</td>
					</TR>
					<TR>
					  <th>660.4</th>
					  <th>650A</th>
					  <th>26</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>1.43</td>
					  <td>1.52</td>
					  <td>1.52</td>
					  <td>1.65</td>
					  <td>1.65</td>
					  <td>1.75</td>
					</TR>
					<TR>
					  <th>711.2</th>
					  <th>700A</th>
					  <th>28</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>1.43</td>
					  <td>1.52</td>
					  <td>1.52</td>
					  <td>1.65</td>
					  <td>1.65</td>
					  <td>1.75</td>
					</TR>
					<TR>
					  <th>762.0</th>
					  <th>750A</th>
					  <th>30</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.28</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.35</td>
					  <td>1.43</td>
					  <td>1.43</td>
					  <td>1.52</td>
					  <td>1.52</td>
					  <td>1.65</td>
					  <td>1.65</td>
					  <td>1.75</td>
					</TR>
					<TR>
					  <th>812.8</th>
					  <th>800A</th>
					  <th>32</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.50</td>
					  <td>1.50</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.75</td>
					  <td>1.75</td>
					  <td>1.85</td>
					</TR>
					<TR>
					  <th>863.6</th>
					  <th>850A</th>
					  <th>34</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.50</td>
					  <td>1.50</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.75</td>
					  <td>1.75</td>
					  <td>1.85</td>
					</TR>
					<TR>
					  <th>914.4</th>
					  <th>900A</th>
					  <th>36</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.50</td>
					  <td>1.50</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.75</td>
					  <td>1.75</td>
					  <td>1.85</td>
					</TR>
					<TR>
					  <th>965.2</th>
					  <th>950A</th>
					  <th>38</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.50</td>
					  <td>1.50</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.75</td>
					  <td>1.75</td>
					  <td>1.85</td>
					</TR>
					<TR>
					  <th>1016.0</th>
					  <th>1000A</th>
					  <th>40</th>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>&nbsp;</TD>
					  <td>1.35</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.40</td>
					  <td>1.50</td>
					  <td>1.50</td>
					  <td>1.60</td>
					  <td>1.60</td>
					  <td>1.75</td>
					  <td>1.75</td>
					  <td>1.85</td>
					</TR>
				  </TABLE>

			</div>

		</div>
	</div>


</div>
<!-- #include file="../inc/footer.asp" -->