<!-- #include file="../inc/top.asp" -->
<link rel="stylesheet" type="text/css" href="../inc/css/sub.css">

<div id="middle_sub">
	<!-- #include file="../inc/sub_visual.asp" -->
	
	<div class="navi_wrap">
		<div class="width_wrap">
			<span class="home">H</span><span class="block1">Product</span><span class="block2">Pipe</span>
		</div>
	</div>

	<div class="width_wrap">
		<!-- #include file="../inc/left.asp" -->
		<div id="contant">
			<h3 class="title">Pipe</h3>

			<!-- #include file="page2_tap.asp" -->
			
			<!-- #include file="page2_navi.asp" -->

			<h6 class="msg underline">Round Pipe Weight</h6>
			
			<div class="table_wrap" style="clear:both;">
				<STYLE type="text/css">
				.table_wrap table td{
					padding:10px 1px 10px 1px;
				}
				</STYLE>
				<table cellpadding="0" cellspacing="0">
					<tr>
					  <th>&nbsp;</td>
					  <th>0.4</th>
					  <th>0.5</th>
					  <th>0.6</th>
					  <th>0.7</th>
					  <th>0.8</th>
					  <th>0.9</th>
					  <th>1.0</th>
					  <th>1.1</th>
					  <th>1.2</th>
					  <th>1.5</th>
					  <th>2.0</th>
					  <th>3.0</th>
					</tr>
					<tr>
					  <td>9.6</td>
					  <td>0.0916</td>
					  <td>0.113</td>
					  <td>0.135</td>
					  <td>0.155</td>
					  <td>0.175</td>
					  <td>0.195</td>
					  <td>0.214</td>
					  <td>0.233</td>
					  <td>0.251</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>12.7</td>
					  <td>&nbsp;</td>
					  <td>0.152</td>
					  <td>0.181</td>
					  <td>0.209</td>
					  <td>0.237</td>
					  <td>0.265</td>
					  <td>0.291</td>
					  <td>0.318</td>
					  <td>0.344</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>15.8</td>
					  <td>&nbsp;</td>
					  <td>0.191</td>
					  <td>0.227</td>
					  <td>0.263</td>
					  <td>0.299</td>
					  <td>0.334</td>
					  <td>0.369</td>
					  <td>0.403</td>
					  <td>0.436</td>
					  <td>0.534</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>19.1</td>
					  <td>&nbsp;</td>
					  <td>0.232</td>
					  <td>0.277</td>
					  <td>0.321</td>
					  <td>0.365</td>
					  <td>0.408</td>
					  <td>0.451</td>
					  <td>0.493</td>
					  <td>0.535</td>
					  <td>0.658</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>22.3</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.480</td>
					  <td>0.531</td>
					  <td>0.581</td>
					  <td>0.631</td>
					  <td>0.777</td>
					  <td>1.011</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;25.4</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.431</td>
					  <td>0.490</td>
					  <td>0.549</td>
					  <td>0.608</td>
					  <td>0.666</td>
					  <td>0.723</td>
					  <td>0.893</td>
					  <td>1.166</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;27.2</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.526</td>
					  <td>0.590</td>
					  <td>0.653</td>
					  <td>0.715</td>
					  <td>0.777</td>
					  <td>0.960</td>
					  <td>1.255</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;31.8</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.542</td>
					  <td>0.618</td>
					  <td>0.693</td>
					  <td>0.767</td>
					  <td>0.841</td>
					  <td>0.915</td>
					  <td>1.132</td>
					  <td>1.485</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;34.0</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.742</td>
					  <td>0.822</td>
					  <td>0.901</td>
					  <td>0.980</td>
					  <td>1.214</td>
					  <td>1.594</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;38.1</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.652</td>
					  <td>0.743</td>
					  <td>0.834</td>
					  <td>0.924</td>
					  <td>1.014</td>
					  <td>1.103</td>
					  <td>1.368</td>
					  <td>1.799</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;42.7</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.835</td>
					  <td>0.937</td>
					  <td>1.039</td>
					  <td>1.140</td>
					  <td>1.241</td>
					  <td>1.539</td>
					  <td>2.028</td>
					  <td>&nbsp;</td>
					</tr>
					<tr>
					  <td>&nbsp;50.8</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>0.996</td>
					  <td>1.119</td>
					  <td>1.241</td>
					  <td>1.362</td>
					  <td>1.483</td>
					  <td>1.842</td>
					  <td>2.431</td>
					  <td>3.572</td>
					</tr>
					<tr>
					  <td>&nbsp;63.5</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>1.249</td>
					  <td>1.403</td>
					  <td>1.557</td>
					  <td>1.710</td>
					  <td>1.862</td>
					  <td>2.317</td>
					  <td>3.064</td>
					  <td>4.521</td>
					</tr>
					<tr>
					  <td>&nbsp;76.3</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;1.505</td>
					  <td>&nbsp;1.690</td>
					  <td>1.876</td>
					  <td>2.061</td>
					  <td>2.245</td>
					  <td>2.795</td>
					  <td>3.702</td>
					  <td>5.478</td>
					</tr>
					<tr>
					  <td>89.1</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>2.195</td>
					  <td>2.411</td>
					  <td>2.628</td>
					  <td>3.273</td>
					  <td>4.339</td>
					  <td>6.434</td>
					</tr>
					<tr>
					  <td>96.0</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>2.366</td>
					  <td>2.600</td>
					  <td>2.834</td>
					  <td>3.531</td>
					  <td>4.683</td>
					  <td>6.950</td>
					</tr>
					<tr>
					  <td>101.6</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>2.009</td>
					  <td>2.258</td>
					  <td>2.506</td>
					  <td>2.754</td>
					  <td>3.001</td>
					  <td>3.740</td>
					  <td>4.962</td>
					  <td>7.368</td>
					</tr>
					<tr>
					  <td>127.0</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>3.139</td>
					  <td>3.450</td>
					  <td>3.760</td>
					  <td>4.689</td>
					  <td>6.228</td>
					  <td>9.267</td>
					</tr>
					<tr>
					  <td>152.4</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>5.638</td>
					  <td>7.493</td>
					  <td>11.165</td>
					</tr>
					<tr>
					  <td>165.2</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>8.130</td>
					  <td>12.121</td>
					</tr>
					<tr>
					  <td>216.3</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>&nbsp;</td>
					  <td>10.676</td>
					  <td>15.940</td>
					</tr>
				  </table>

			</div>

		</div>
	</div>


</div>
<!-- #include file="../inc/footer.asp" -->